name: sas_python
channels:
    - conda-forge
dependencies:
    - python>=3.10
    - ipython
    - jupyterlab
    - notebook
    - pandas
    - matplotlib
    - scipy
    - numpy
    - scikit-learn
    - ipykernel
    - seaborn
